import { jsPDF } from "jspdf";
import type { AnalyzeResult } from "./signal-types";

export function exportTradePlanPdf(data: AnalyzeResult, backtest?: { winRate: number | null; decided: number; wins: number } | null) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  const M = 48;
  let y = M;

  const tp = data.signal.trade_plan;
  const dir = data.signal.direction;
  const dirColor: [number, number, number] =
    dir === "BUY" ? [22, 163, 74] : dir === "SELL" ? [220, 38, 38] : [100, 116, 139];

  // Header
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("AI Trade Plan", M, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(120);
  doc.text(new Date(data.generatedAt).toLocaleString(), W - M, y, { align: "right" });
  y += 22;
  doc.setDrawColor(220);
  doc.line(M, y, W - M, y);
  y += 24;

  // Asset block
  doc.setTextColor(0);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text(`${data.name}  (${data.symbol})`, M, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Timeframe: ${data.interval}  ·  HTF context: ${data.htfInterval}  ·  Source: ${data.source}`, M, y + 14);
  y += 38;

  // Direction badge
  doc.setFillColor(...dirColor);
  doc.roundedRect(M, y, 110, 36, 6, 6, "F");
  doc.setTextColor(255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text(dir, M + 55, y + 23, { align: "center" });

  doc.setTextColor(0);
  doc.setFontSize(11);
  doc.text(`Confidence: ${Math.round(data.signal.confidence)}%`, M + 130, y + 15);
  doc.text(`HTF alignment: ${data.signal.htf_alignment}`, M + 130, y + 30);
  y += 56;

  // Trade plan
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Trade Plan", M, y);
  y += 6;
  doc.setDrawColor(230);
  doc.line(M, y, W - M, y);
  y += 18;

  if (tp.valid) {
    const risk = Math.abs(tp.entry - tp.stop_loss);
    const reward = Math.abs(tp.take_profit - tp.entry);
    const rr = risk > 0 ? reward / risk : 0;
    const rows: Array<[string, string]> = [
      ["Entry", tp.entry.toFixed(2)],
      ["Stop-loss", tp.stop_loss.toFixed(2)],
      ["Take-profit", tp.take_profit.toFixed(2)],
      ["Risk / Reward", `1 : ${rr.toFixed(2)}`],
    ];
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    rows.forEach(([k, v]) => {
      doc.setTextColor(110);
      doc.text(k, M, y);
      doc.setTextColor(0);
      doc.text(v, M + 160, y);
      y += 18;
    });
  } else {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(11);
    doc.setTextColor(110);
    doc.text("No trade plan — signal is NEUTRAL.", M, y);
    y += 18;
  }
  y += 10;

  // Indicators
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(0);
  doc.text("Indicators", M, y);
  y += 6;
  doc.line(M, y, W - M, y);
  y += 18;
  const ind = data.indicators;
  const indRows: Array<[string, string]> = [
    ["Last close", ind.lastClose.toFixed(2)],
    ["Change vs prev", `${ind.changePct >= 0 ? "+" : ""}${ind.changePct.toFixed(2)}%`],
    ["RSI(14)", ind.rsi14.toFixed(2)],
    ["SMA(20) / SMA(50)", `${ind.sma20.toFixed(2)} / ${ind.sma50.toFixed(2)}`],
    ["MACD hist", ind.macd.histogram.toFixed(4)],
    ["60-candle range", `${ind.low60.toFixed(2)} – ${ind.high60.toFixed(2)}`],
    ["Support / Resistance", `${data.signal.key_levels.support.toFixed(2)} / ${data.signal.key_levels.resistance.toFixed(2)}`],
  ];
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  indRows.forEach(([k, v]) => {
    doc.setTextColor(110);
    doc.text(k, M, y);
    doc.setTextColor(0);
    doc.text(v, M + 200, y);
    y += 16;
  });
  y += 10;

  // Backtest
  if (backtest && backtest.decided > 0 && backtest.winRate != null) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text("Backtest Summary", M, y);
    y += 6;
    doc.line(M, y, W - M, y);
    y += 18;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.setTextColor(110);
    doc.text("Win-rate", M, y);
    doc.setTextColor(0);
    doc.text(`${(backtest.winRate * 100).toFixed(1)}%  (${backtest.wins}/${backtest.decided})`, M + 200, y);
    y += 22;
  }

  // Rationale
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(0);
  doc.text("Rationale", M, y);
  y += 6;
  doc.line(M, y, W - M, y);
  y += 18;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  const rationaleLines = doc.splitTextToSize(data.signal.rationale, W - M * 2);
  doc.text(rationaleLines, M, y);
  y += rationaleLines.length * 14 + 20;

  // Footer
  doc.setFont("helvetica", "italic");
  doc.setFontSize(9);
  doc.setTextColor(150);
  const footer = "Educational analysis only — not financial advice. Generated by SignalDesk.";
  doc.text(footer, W / 2, doc.internal.pageSize.getHeight() - 24, { align: "center" });

  const fname = `trade-plan_${data.symbol}_${data.interval}_${new Date(data.generatedAt)
    .toISOString()
    .replace(/[:.]/g, "-")}.pdf`;
  doc.save(fname);
}